// src/components/Footer.vue
<script setup lang="ts">
const buildTime = __BUILD_TIME__

const timeAgo = useTimeAgo(new Date(buildTime))
</script>

<template>
  <div class="relative">
    <!-- Social pill — bottom left -->
    <div class="absolute bottom-4 left-4 hidden md:flex items-center gap-0.5 rounded-full border bg-background/80 p-1 shadow-sm backdrop-blur">
      <a
        href="https://www.threads.com/@brokariim"
        target="_blank"
        rel="noreferrer"
        aria-label="Follow on Threads"
        class="flex size-8 items-center justify-center rounded-full text-muted-foreground transition-[color,background-color] hover:bg-accent hover:text-foreground"
      >
        <svg
          viewBox="0 0 24 24"
          width="16"
          height="16"
          fill="currentColor"
          aria-hidden="true"
        >
          <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231 5.45-6.231Zm-1.161 17.52h1.833L7.084 4.126H5.117l11.966 15.644Z" />
        </svg>
      </a>
      <a
        href="https://github.com/BroKarim"
        target="_blank"
        rel="noreferrer"
        aria-label="View source on GitHub"
        class="flex size-8 items-center justify-center rounded-full text-muted-foreground transition-[color,background-color] hover:bg-accent hover:text-foreground"
      >
        <svg
          viewBox="0 0 16 16"
          width="18"
          height="18"
          fill="currentColor"
          aria-hidden="true"
        >
          <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82a7.42 7.42 0 0 1 2-.27c.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8Z" />
        </svg>
      </a>
    </div>

    <footer class="text-center text-sm pt-8 pb-6">
      <p class="color-fade">
        maintained by
        <a
          class="opacity-75 hover:opacity-100"
          href="https://github.com/BroKarim"
          target="_blank"
        >Brokarim</a>,
        powered by
        <a
          class="opacity-75 hover:opacity-100"
          href="https://iconify.design"
          target="_blank"
        >Iconify</a>
      </p>
      <div color-fade mt-1 op50 italic>
        Last update: {{ buildTime }} ({{ timeAgo }})
      </div>
    </footer>
  </div>
</template>

// src/components/new-home/footer.tsx
import { XIcon, DiscordIcon } from "./icons";

export function ShoogleFooter() {
  return (
    <footer className="absolute inset-x-0 bottom-0 z-10 flex flex-wrap items-center justify-between gap-x-1 gap-y-2 px-4 py-2.5 pb-[max(0.625rem,env(safe-area-inset-bottom))] md:h-10 md:py-0 md:px-10">
      <nav className="flex flex-wrap items-center justify-center gap-1">
        <a
          href="/shoggle/terms-of-service"
          className="relative inline-flex shrink-0 cursor-pointer items-center justify-center whitespace-nowrap rounded-lg border border-transparent font-medium outline-none hover:underline underline-offset-4 h-auto px-2 py-1 text-xs text-muted-foreground"
        >
          Terms of Service
        </a>
        <a
          href="/shoggle/privacy-policy"
          className="relative inline-flex shrink-0 cursor-pointer items-center justify-center whitespace-nowrap rounded-lg border border-transparent font-medium outline-none hover:underline underline-offset-4 h-auto px-2 py-1 text-xs text-muted-foreground"
        >
          Privacy Policy
        </a>
      </nav>
      <div className="flex items-center gap-0.5">
        <a
          href="https://x.com/alibey_10"
          target="_blank"
          rel="noopener noreferrer"
          aria-label="Follow on X (Twitter)"
          className="relative inline-flex shrink-0 cursor-pointer items-center justify-center whitespace-nowrap rounded-lg border border-transparent font-medium outline-none hover:bg-accent h-auto px-2 py-1 text-muted-foreground"
        >
          <XIcon className="size-3.5" />
        </a>
        <a
          href="/shadcord"
          target="_blank"
          rel="noopener noreferrer"
          aria-label="Join Shadcord on Discord"
          className="relative inline-flex shrink-0 cursor-pointer items-center justify-center whitespace-nowrap rounded-lg border border-transparent font-medium outline-none hover:bg-accent h-auto px-2 py-1 text-muted-foreground"
        >
          <DiscordIcon className="size-3.5" />
        </a>
      </div>
    </footer>
  );
}
